<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cari</name>
   <tag></tag>
   <elementGuidId>074eb148-108c-47c6-b11a-205007e05cca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topActionHeader']/div/div[2]/div/div[2]/div/form/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.search-box__button--1oH7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Cari&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>af4a9762-fd2e-4adf-9c5f-ca0de0b94833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>//www.lazada.co.id/catalog/?spm=a2o4j.homepage.search.d_go.579953e0sijlux&amp;q=iphone%2015%20pro</value>
      <webElementGuid>a17070cc-124f-46c4-84c1-8d06aba547d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-box__button--1oH7</value>
      <webElementGuid>a7233848-0904-49af-ad21-cc3a06a4b499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d6e7a79a-0aac-419f-9f56-e77b7a97b77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-click</name>
      <type>Main</type>
      <value>gostr=/lzdpub.header.search;locaid=d_go</value>
      <webElementGuid>c4668cbe-e151-49b9-96bb-19e27dae351a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>3004a037-025a-4afe-bb70-753aaad4d3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-anchor-id</name>
      <type>Main</type>
      <value>a2o4j.homepage.search.d_go</value>
      <webElementGuid>31b7a0fd-1a03-40f6-88d3-52d5a45009c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cari</value>
      <webElementGuid>5d3cb815-04a4-4b35-a2c8-dc39a140e97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topActionHeader&quot;)/div[@class=&quot;lzd-header-content&quot;]/div[@class=&quot;lzd-logo-bar home&quot;]/div[@class=&quot;logo-bar-content header-content&quot;]/div[@class=&quot;lzd-nav-search&quot;]/div[@class=&quot;layout-search-box--qK-K&quot;]/form[1]/div[@class=&quot;search-box--2I2a&quot;]/div[@class=&quot;search-box__search--2fC5&quot;]/a[@class=&quot;search-box__button--1oH7&quot;]</value>
      <webElementGuid>ce5e4674-b847-4d12-b2a3-def7981267cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topActionHeader']/div/div[2]/div/div[2]/div/form/div/div[2]/a</value>
      <webElementGuid>fc753949-ee04-4688-9af0-784b7135c97e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cari')]</value>
      <webElementGuid>22ace111-e54b-43c5-a401-b76dfb4e2517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iphone 15 pro'])[1]/preceding::a[1]</value>
      <webElementGuid>1ad25588-78bf-4100-ba4e-d294813382ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cari']/parent::*</value>
      <webElementGuid>1d592e2d-fa4a-415e-a122-9a7965aaf285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '//www.lazada.co.id/catalog/?spm=a2o4j.homepage.search.d_go.579953e0sijlux&amp;q=iphone%2015%20pro')]</value>
      <webElementGuid>e3f7fd68-8acc-4501-9675-cacb3f8e55d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/a</value>
      <webElementGuid>d96d1a95-7520-4057-b4b3-d1ef692cd7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '//www.lazada.co.id/catalog/?spm=a2o4j.homepage.search.d_go.579953e0sijlux&amp;q=iphone%2015%20pro' and (text() = 'Cari' or . = 'Cari')]</value>
      <webElementGuid>8aa8500a-3b4a-4fd5-af75-482f7bb8c078</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
