<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cari_1</name>
   <tag></tag>
   <elementGuidId>0161757d-6416-4c56-942a-2c222ea7e7ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topActionHeader']/div/div[2]/div/div[2]/div/form/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.search-box__button--1oH7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Cari&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>93ceac57-4f67-486a-91c6-5e8f7d7d6c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>//www.lazada.co.id/catalog/?spm=a2o4j.homepage.search.d_go.579953e0R5TvpX&amp;q=iphone%2015%20pro</value>
      <webElementGuid>90f43374-9e94-48c0-8113-ef08f74dcf57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-box__button--1oH7</value>
      <webElementGuid>afe443f8-7545-4b90-b8cc-8751c99a67b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7d573a3e-939a-4e3c-9acf-47eb273b52c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-click</name>
      <type>Main</type>
      <value>gostr=/lzdpub.header.search;locaid=d_go</value>
      <webElementGuid>52a95784-15f3-4ae5-a272-2a6927074403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>9778fe16-d495-4874-b950-3ca966820e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-anchor-id</name>
      <type>Main</type>
      <value>a2o4j.homepage.search.d_go</value>
      <webElementGuid>d30f8e01-d62d-49bc-a1ec-2951d4d31f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cari</value>
      <webElementGuid>b7239d4d-bb30-439d-90f7-1c0c797da6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topActionHeader&quot;)/div[@class=&quot;lzd-header-content&quot;]/div[@class=&quot;lzd-logo-bar home&quot;]/div[@class=&quot;logo-bar-content header-content&quot;]/div[@class=&quot;lzd-nav-search&quot;]/div[@class=&quot;layout-search-box--qK-K&quot;]/form[1]/div[@class=&quot;search-box--2I2a&quot;]/div[@class=&quot;search-box__search--2fC5&quot;]/a[@class=&quot;search-box__button--1oH7&quot;]</value>
      <webElementGuid>1523d1ea-344c-4c25-96b2-7c98c60b7c2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topActionHeader']/div/div[2]/div/div[2]/div/form/div/div[2]/a</value>
      <webElementGuid>abc147b3-4c29-4056-8f96-d63be04f8138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cari')]</value>
      <webElementGuid>392e27cf-c153-49fe-92ed-ccd49541c06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iphone 15 pro'])[1]/preceding::a[1]</value>
      <webElementGuid>1a2a5b66-d0ff-4b49-9152-d442084f98d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cari']/parent::*</value>
      <webElementGuid>4da3cfbf-6293-4104-85f7-174450f5b391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '//www.lazada.co.id/catalog/?spm=a2o4j.homepage.search.d_go.579953e0R5TvpX&amp;q=iphone%2015%20pro')]</value>
      <webElementGuid>d3609ea8-2e4a-411c-931b-97020755e968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/a</value>
      <webElementGuid>a3e38d19-3aad-4743-968a-86b43a984fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '//www.lazada.co.id/catalog/?spm=a2o4j.homepage.search.d_go.579953e0R5TvpX&amp;q=iphone%2015%20pro' and (text() = 'Cari' or . = 'Cari')]</value>
      <webElementGuid>995be32c-9b4a-4b57-98b8-0707f4927cd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
