<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rp19.249.000</name>
   <tag></tag>
   <elementGuidId>a08de6e0-d9c5-448a-974d-478042dd6e33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='module_product_price_1']/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.notranslate.pdp-price.pdp-price_type_normal.pdp-price_color_orange.pdp-price_size_xl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Rp19.249.000&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>711a860d-ed42-46df-a2a3-e49c5a3fff16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notranslate pdp-price pdp-price_type_normal pdp-price_color_orange pdp-price_size_xl</value>
      <webElementGuid>3eb85407-bd58-4c70-9ba3-6f91b3cbb209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-anchor-id</name>
      <type>Main</type>
      <value>a2o4j.pdp_revamp.0.i0.32283f98IO40YZ</value>
      <webElementGuid>14d025b0-b7e2-48b2-adf2-cee39ab30bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp19.249.000</value>
      <webElementGuid>2ebaeece-69c9-4dca-aaa9-4c4e7e15222e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;module_product_price_1&quot;)/div[@class=&quot;pdp-mod-product-price&quot;]/div[@class=&quot;pdp-product-price&quot;]/span[@class=&quot;notranslate pdp-price pdp-price_type_normal pdp-price_color_orange pdp-price_size_xl&quot;]</value>
      <webElementGuid>64d9fd82-b379-4361-be97-87f45d43ea63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='module_product_price_1']/div/div/span</value>
      <webElementGuid>16b3d26c-4ebd-4716-a3fd-191d64072f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lebih banyak Smartphones dari Apple'])[1]/following::span[1]</value>
      <webElementGuid>f5c7cd69-f337-4b5b-b0a5-46cb092f40af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apple'])[1]/following::span[1]</value>
      <webElementGuid>32944109-9895-489d-8728-515f6d20fd1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cicilan'])[1]/preceding::span[3]</value>
      <webElementGuid>13845779-40cb-4cd3-8197-ce070a73493d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rp19.249.000']/parent::*</value>
      <webElementGuid>69eb4857-f093-4d9d-a119-be6e3e890433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/span</value>
      <webElementGuid>68dd2176-c7e4-4384-bd64-b52517a72f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Rp19.249.000' or . = 'Rp19.249.000')]</value>
      <webElementGuid>3c81e727-f8b2-4406-99de-6affe60ef3b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
