<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Apple iPhone 15 Pro</name>
   <tag></tag>
   <elementGuidId>5b3edc85-9177-4462-ad37-106cd4baf7e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Apple iPhone 15 Pro&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Apple iPhone 15 Pro&quot;s] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>74248bbf-dac4-4a03-90d2-dd302ebda300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>age</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d1ff8e35-e367-46d5-aa72-0169634a8cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>//www.lazada.co.id/products/apple-iphone-15-pro-i7733246955.html?spm=a2o4j.searchlist.list.2.6d694589Eflzqq</value>
      <webElementGuid>e0b64dbc-8e8b-4548-9167-22cd06499e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Apple iPhone 15 Pro</value>
      <webElementGuid>5f09b2bb-74f7-4858-840a-abe1196dca96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-anchor-id</name>
      <type>Main</type>
      <value>a2o4j.searchlist.list.2</value>
      <webElementGuid>7491fad3-4b51-4323-827b-9874b4dfd5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apple iPhone 15 Pro</value>
      <webElementGuid>4399ee73-cd98-47a8-96fb-4627fd40565d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;FWSEp&quot;]/div[@class=&quot;ant-row FrEdP css-1bkhbmc app&quot;]/div[@class=&quot;ant-col ant-col-24 css-1bkhbmc app&quot;]/div[@class=&quot;ant-row css-1bkhbmc app&quot;]/div[@class=&quot;ant-col ant-col-20 ant-col-push-4 Jv5R8 css-1bkhbmc app&quot;]/div[@class=&quot;_17mcb&quot;]/div[@class=&quot;Bm3ON&quot;]/div[@class=&quot;Ms6aG&quot;]/div[@class=&quot;qmXQo&quot;]/div[@class=&quot;buTCk&quot;]/div[@class=&quot;RfADt&quot;]/a[1]</value>
      <webElementGuid>1bf4ae0e-5410-487b-8079-723017c11226</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[2]/a</value>
      <webElementGuid>8c6fc442-e31f-444f-87aa-468fb205d94f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Apple iPhone 15 Pro')]</value>
      <webElementGuid>d093a016-81f5-4c58-94d0-a435c0146096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat:'])[1]/following::a[2]</value>
      <webElementGuid>af7ba4a0-3a01-43d4-8597-bfab39a0f76d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terkait'])[1]/following::a[2]</value>
      <webElementGuid>8cf33225-3ac1-46c5-84bc-13287d72899e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp19.249.000'])[1]/preceding::a[1]</value>
      <webElementGuid>75f07a75-c979-4aaa-80a7-13e663f0e669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(50)'])[1]/preceding::a[1]</value>
      <webElementGuid>73e4592e-8859-41d7-af79-739237c94881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apple iPhone 15 Pro']/parent::*</value>
      <webElementGuid>1e00674d-6faa-488b-a4df-0eecac1ac346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '//www.lazada.co.id/products/apple-iphone-15-pro-i7733246955.html?spm=a2o4j.searchlist.list.2.6d694589Eflzqq')]</value>
      <webElementGuid>26b901d8-67d4-49c0-bd7d-c6e0146c0039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div[2]/a</value>
      <webElementGuid>af1a1748-4079-4eef-ad59-15cbe88248b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '//www.lazada.co.id/products/apple-iphone-15-pro-i7733246955.html?spm=a2o4j.searchlist.list.2.6d694589Eflzqq' and @title = 'Apple iPhone 15 Pro' and (text() = 'Apple iPhone 15 Pro' or . = 'Apple iPhone 15 Pro')]</value>
      <webElementGuid>80397e61-c29b-4830-81f9-c07ab7482001</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
